AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template to create EC2 instance with security group

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-04a81a99f5ec58529
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref SSHSecurityGroup
        - !Ref ServerSecurityGroup
      KeyName: academykeypair
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # sudo apt -y install git
          sudo apt -y update
          sudo apt -y upgrade
          sudo git clone https://github.com/kevwong16/wordpress-project.git /root/wordpress-project
          sudo chmod -R 755 /root/wordpress-project
          sudo bash /root/wordpress-project/lemp-setup.sh

  # our EC2 security group
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22

  # our second EC2 security group
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable accessing server via port 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
