name: Test and Deploy Bash Script

on:
  push:
    branches:
      - setup
      
env:
  CF_API: ${{ secrets.CF_API }}
  CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug SSH connection
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key
        ssh -i private_key -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "echo 'SSH Connection Successful'"

    - name: Edit CF Variables
      run: |
        sed -i 's/REPLACE_CF_API/${{ secrets.CF_API }}/g' ./lemp-setup.sh
        sed -i 's/REPLACE_CF_ZONE_ID/${{ secrets.CF_ZONE_ID }}/g' ./lemp-setup.sh
        

    - name: Copy files to VM
      run: |
        scp -i private_key -o StrictHostKeyChecking=no -P ${{ secrets.PORT }} * ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:~
